zstyle ':omz:plugins:eza' 'dirs-first'  "yes"
zstyle ':omz:plugins:eza' 'git-status'  "yes"
zstyle ':omz:plugins:eza' 'header'      "yes"
zstyle ':omz:plugins:eza' 'icons'       "yes"
zstyle ':omz:plugins:eza' 'size-prefix' "binary"